# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: hmatch

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check style
      run: pip install pre-commit && pre-commit run --all

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v ./... -cover

    - name: Test CLI
      run: |
        go run main.go fit -h
        go run main.go fit samples/sample.wav
        go run main.go combine 352000000,003421000
